# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- 2.1

pr: none

name: 2.1.$(Rev:r)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'

- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**\AssemblyInfo.cs'
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    Title: 'Code Endeavors Resource Manager'
    Description: 'Code Endeavors Resource Manager'
    Company: 'Code Endeavors, Inc.'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false

- task: VSBuild@1
  inputs:
    solution: '**\*.sln'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '$(Build.SourcesDirectory)/redist/CodeEndeavors.ResourceManager.File.nuspec'
    versioningScheme: byBuildNumber
    packDestination: '$(Build.SourcesDirectory)/redist'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '$(Build.SourcesDirectory)/redist/CodeEndeavors.ResourceManager.ServiceHost.nuspec'
    versioningScheme: byBuildNumber
    packDestination: '$(Build.SourcesDirectory)/redist'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '$(Build.SourcesDirectory)/redist/CodeEndeavors.ResourceManager.SQLServer.nuspec'
    versioningScheme: byBuildNumber
    packDestination: '$(Build.SourcesDirectory)/redist'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '$(Build.SourcesDirectory)/redist/CodeEndeavors.Services.ResourceManager.ClientX.nuspec'
    versioningScheme: byBuildNumber
    packDestination: '$(Build.SourcesDirectory)/redist'    

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '$(Build.SourcesDirectory)/redist/CodeEndeavors.ResourceManager.nuspec'
    versioningScheme: byBuildNumber
    packDestination: '$(Build.SourcesDirectory)/redist'      

# - task: NuGetCommand@2
#   displayName: 'NuGet push'
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.SourcesDirectory)/redist/*.nupkg'
#     nuGetFeedType: 'internal'
#     publishVstsFeed: 'ac758a19-2517-4b8d-9d83-43bd02106e50'
#     allowPackageConflicts: false

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.SourcesDirectory)/redist/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.org'

